### ISSUE TITLE
Add support for mouse events

### ISSUE THREAD

**Issue by ccbrown** [ccbrown/iocraft#17]
It would be great to be able to click, scroll, hover, etc. with the mouse.

Implementing this support for fullscreen mode is pretty trivial. The problem is...

- Capturing mouse events hijacks scrolling, which is very undesirable when the interface is not a fullscreen one.
- There's no apparent way to convert XY coordinates to be relative to UI elements when not fullscreen.

Is there a robust way to accomplish this? Are there other libraries that do it well?

**Comment by skreborn** [comment]
I would argue that these features don't make much sense in a non-fullscreen application in the first place, so perhaps the way forward is simply to reserve this functionality to those that have real use for it. Is it really worth trying to find workarounds? Is there a use-case to consider?

**Comment by ccbrown** [comment]
Good question. I don't have any particularly strong use-cases in mind other than "clickable buttons and text fields might look nice", so perhaps the way to go is to start with implementing this for fullscreen mode and see what use-cases aren't met after that.

**Comment by ccbrown** [comment]
The next release will have support for mouse events and to demonstrate it, there's a new calculator example:

<img width="738" alt="calculator" src="https://github.com/user-attachments/assets/6155f2c4-2156-4f1d-8f91-c477e482711e">
