### ISSUE TITLE
gap not working as expected

### ISSUE THREAD

**Issue by milesj** [ccbrown/iocraft#52]
Coming from CSS, the gap property here doesn't work the same as it does in CSS. I expected the gap to be in between each element in a uniform fashion, but instead it looks like gap simply adds left/right or top/bottom padding to each element. Demonstrated here:

<img width="769" alt="Screenshot 2024-12-26 at 1 02 47 PM" src="https://github.com/user-attachments/assets/1b6c59a0-3196-4752-841c-eb5b6eb83c44" />

I'm not sure if this is an iocraft or taffy issue. I looked through taffy's issues, but didn't see anything about this.

**Comment by ccbrown** [comment]
Hmm... My instinct is that this is a Taffy issue since iocraft just passes properties through and doesn't really have any layout logic itself. I'll investigate and report upstream if necessary.

Thanks for reporting!

**Comment by ccbrown** [comment]
Do you have a minimal example that reproduces this issue? At first glance, I'm not seeing the same issue. There's a Taffy example here which seems to have the right behavior:

https://github.com/DioxusLabs/taffy/blob/main/examples/flexbox_gap.rs

And an iocraft test here which also seems to behave correctly:

https://github.com/ccbrown/iocraft/blob/98f2a52/packages/iocraft/src/components/box.rs#L578

**Comment by milesj** [comment]
Here's a stacked example with gap 0.

<img width="280" alt="Screenshot 2024-12-26 at 9 16 26 PM" src="https://github.com/user-attachments/assets/3251eaa6-ece0-404b-a234-3130317edfd5" />

And with gap 1.

<img width="277" alt="Screenshot 2024-12-26 at 9 16 31 PM" src="https://github.com/user-attachments/assets/33aa4896-f757-4396-8bcb-943e41d4b83d" />

Looks like each row has top and bottom padding of 1, except the last row which has no bottom...

Tried both `gap` and `row_gap`. This is the component: https://github.com/moonrepo/starbase/blob/master/crates/console/src/components/layout.rs#L46

**Comment by milesj** [comment]
Ok this is confusing. I created a more basic example, and that does work.

<img width="611" alt="Screenshot 2024-12-26 at 9 21 30 PM" src="https://github.com/user-attachments/assets/a4865e1b-300d-425b-b846-40fb918b07ad" />

**Comment by milesj** [comment]
Another example of it not working correctly. Top = no gap, bottom = gap 1. Notice the button horizontal spacing.

<img width="411" alt="Screenshot 2024-12-26 at 9 23 33 PM" src="https://github.com/user-attachments/assets/a9f42dfd-f87c-49e0-9f4b-ce2039dccefa" />

**Comment by ccbrown** [comment]
Thanks! I see what's going on here. The fix is trivial. I'll write some tests and get it in tomorrow.

**Comment by ccbrown** [comment]
This should be fixed in main (commit `fd48f170e6f93eb83e2b2225455e5551b1239367`). I'll put out a bug fix release soon. If you'd like to go ahead and confirm that commit resolves this for you, it'd be appreciated. Thanks!

**Comment by milesj** [comment]
Tested a few scenarios and they all work 👍

**Comment by ccbrown** [comment]
Resolved in 0.5.3.
